# Generated by Django 2.1.7 on 2019-03-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_tipo',
        ),
    ]
