# Generated by Django 2.1.7 on 2019-03-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_usuario_usuario_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
    ]
