# Generated by Django 2.1.7 on 2019-03-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('cotacao', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('tipo', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('data', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('empresa', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('min52', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('setor', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('max52', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('subsetor', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('volume', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('valor_de_mercado', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('ultimo_balanco', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('valor_firma', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('num_acoes', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('PL', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('PVP', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('PEBIT', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('PSR', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('PAtivos', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('PCap_Giro', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('PAtivCircLiq', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('dividend_yield', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('ev_ebit', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('giro_ativos', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('crescimento_receita5', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('LPA', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('VPA', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('marg_bruta', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('marg_EBIT', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('marg_liquida', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('EBIT_ATIVO', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('ROIC', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('ROE', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('liquidez_corr', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('diBrPat', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('ativo', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('disponibilidades', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('ativo_circulante', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('div_bruta', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('div_liquida', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('patrim_liq', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('receita_liq12', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('EBIT12', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('Lucro_liq12', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('receita_liq3', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('EBIT3', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('lucro_liq3', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
            ],
        ),
    ]
