# Generated by Django 2.1.7 on 2019-03-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginafiltro', '0002_auto_20190310_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='lucro_liq3',
            field=models.BigIntegerField(default=0),
        ),
    ]
