# Generated by Django 2.1.7 on 2019-03-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginafiltro', '0003_auto_20190310_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='EBIT12',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='EBIT3',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Lucro_liq12',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ativo',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ativo_circulante',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='disponibilidades',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='div_bruta',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='div_liquida',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='patrim_liq',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='receita_liq12',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='receita_liq3',
            field=models.BigIntegerField(default=0),
        ),
    ]
