# Generated by Django 2.1.7 on 2019-03-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginafiltro', '0004_auto_20190310_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='num_acoes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='valor_de_mercado',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='valor_firma',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='volume',
            field=models.BigIntegerField(default=0),
        ),
    ]
