# Generated by Django 2.1.7 on 2019-03-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginafiltro', '0006_auto_20190311_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='EBIT_ATIVO',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='LPA',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='PAtivCircLiq',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='PAtivos',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='PCap_Giro',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='PEBIT',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='PL',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='PSR',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='PVP',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ROE',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ROIC',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='VPA',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cotacao',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='crescimento_receita5',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='diBrPat',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ev_ebit',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='giro_ativos',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='liquidez_corr',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='marg_EBIT',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='marg_bruta',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='marg_liquida',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='max52',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='min52',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
    ]
